#!/bin/bash
value=127;
waittime=2
name=$(kubectl get pods -o json | jq -r '.items[].metadata |select(.labels."job-name" == "devpod") | .name')
echo -n connecting to $name
while [[ $value -ne 0 ]];
do
    # name=$(kubectl get pods | grep "devpod--" | awk '{ print $1 }')
    kubectl exec -it $name -- bash 2>/dev/null && break;
    value=$?
    echo -n .
    sleep $waittime
done
